/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include <stdint.h>
#include "../RCC/inc/RCC_interface.h"
#include "../AFIO/inc/AFIO_interface.h"
//#include "../NVIC/inc/NVIC_interface.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC_VidInit();
	RCC_voidEnablePeripheral(APB2_BUS, APB2_AFIOEN);
	AFIO_voidSetEXTIConfiguration(AFIO_LINE1,AFIO_PORTB);
	AFIO_voidSetEXTIConfiguration(AFIO_LINE0,AFIO_PORTC);
	AFIO_voidSetEXTIConfiguration(AFIO_LINE15,AFIO_PORTB);
	//NVIC_EnableInterrupt(5);\
	//NVIC_SetPriority(6,7,0);
    /* Loop forever */
	for(;;);
}
